import * as THREE from 'three';
import {createGirl,animateGirl} from '../js/character.js';
import {EASY} from '../js/questions/easy.js';
import {sfx,startBgm,toggleBgm} from '../js/audio.js';
import {buildWorld} from './world.js';

const $=id=>document.getElementById(id);
const renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8ab4c4);scene.fog=new THREE.FogExp2(0x89afbd,.0065);
const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,500);const hemi=new THREE.HemisphereLight(0xd8f3ff,0x39433f,2.2);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe3b0,3.2);sun.position.set(-55,75,-25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-85;sun.shadow.camera.right=85;sun.shadow.camera.top=85;sun.shadow.camera.bottom=-85;scene.add(sun);
const world=buildWorld(scene);const girl=createGirl();girl.scale.setScalar(1.18);girl.position.set(28,0,-106);girl.rotation.y=Math.PI;scene.add(girl);
const SIDE_DATA=[
  {type:'npc',x:-18,z:-61,prompt:'聽校友分享',text:'九龍公園前身曾是軍營，現在是市中心的大型綠洲。',value:20},
  {type:'npc',x:43,z:-42,prompt:'聽同學提示',text:'一直沿指南針走，金色圓點就是下一個地標！',value:20},
  {type:'npc',x:-57,z:27,prompt:'聽香港故事',text:'天星小輪自十九世紀起連接九龍與香港島。',value:20},
  {type:'npc',x:25,z:50,prompt:'聽藝術故事',text:'星光大道表揚香港電影工作者的創意。',value:20},
  {type:'food',x:-39,z:-102,prompt:'品嚐雞蛋仔',text:'香脆雞蛋仔！移動加速 10 秒。',value:30},
  {type:'food',x:-35,z:-116,prompt:'品嚐魚蛋',text:'咖喱魚蛋補充探險能量！移動加速 10 秒。',value:30},
  {type:'dog',x:-20,z:-53,prompt:'跟小狗做朋友',text:'小狗加入了你的探索隊！',value:50},
];
const sideActivities=[];for(const d of SIDE_DATA){if(d.type==='npc'){const model=createGirl();model.scale.setScalar(.88);model.position.set(d.x,0,d.z);scene.add(model);d.model=model}else{const marker=new THREE.Mesh(d.type==='dog'?new THREE.SphereGeometry(.7,12,8):new THREE.ConeGeometry(.7,1.3,6),new THREE.MeshStandardMaterial({color:d.type==='dog'?0xc98c5b:0xffa24d,emissive:d.type==='dog'?0x301408:0x542000,emissiveIntensity:.4}));marker.position.set(d.x,d.type==='dog'?.7:1,d.z);scene.add(marker);d.model=marker}d.done=false;sideActivities.push(d)}
const state={phase:'welcome',mission:0,score:0,coins:0,stars:0,name:'Explorer',near:null,nearSide:null,yaw:0,camYaw:0,camPitch:.42,hitUntil:5,boostUntil:0,dogFollowing:false};const keys={};let joy={x:0,y:0};
const objectiveHints=['向北前往金色地圖圈','向南沿彌敦道前往玻璃大樓','尋找彌敦道旁的多元文化地標','尋找經典綠色屋頂建築','前往前水警總部','向西前往廣東道海旁','走向海旁大型文化建築','在海濱尋找高聳鐘樓','前往白色蛋形建築','前往東面的藝術地標','沿海濱尋找地面金星','往北進入九龍公園','回到九龍公園探索亭','沿東面道路前往紅磚教堂','尋找紅色港鐵入口','前往佐敦著名夜市'];
function updateObjective(){const total=world.missions.length,target=world.missions[state.mission];$('objective').textContent=target?`前往${target.name}`:'展覽修復完成';$('objectiveHint').textContent=target?(objectiveHints[state.mission]||'跟隨指南針與小地圖金點'):'維港星光已重現';$('objectiveCount').textContent=`${state.mission} / ${total}`;$('objectiveFill').style.width=`${state.mission/total*100}%`;$('progressFill').style.width=`${state.mission/total*100}%`;world.missions.forEach((m,i)=>{m.ring.visible=i>=state.mission;m.beam.visible=i===state.mission})}
function updateCollection(){ $('scoreCount').textContent=`SCORE ${state.score}`;$('coinCount').textContent=`● ${state.coins}`;$('starCount').textContent=`★ ${state.stars}`; }
function collide(x,z){if(x<-88||x>88||z<-140||z>75)return true;return world.colliders.some(c=>Math.abs(x-c.x)<c.w/2+1&&Math.abs(z-c.z)<c.d/2+1)}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function interact(){if(state.phase!=='play')return;if(state.near){openQuiz(state.near);return}const d=state.nearSide;if(!d||d.done)return;d.done=true;state.score+=d.value;updateCollection();sfx.coin();if(d.type==='food')state.boostUntil=elapsed+10;if(d.type==='dog')state.dogFollowing=true;toast(`${d.text} +${d.value} 分`)}
let activeMission=null,quizQueue=[],quizIndex=0,quizCorrect=0;
function openQuiz(m){activeMission=m;quizIndex=0;quizCorrect=0;const a=EASY[Math.floor(Math.random()*EASY.length)],b=EASY[Math.floor(Math.random()*EASY.length)];quizQueue=[m.question,a,b];state.phase='quiz';$('quiz').classList.remove('hidden');renderQuizQuestion()}
function renderQuizQuestion(){const q=quizQueue[quizIndex];$('quizPlace').textContent=activeMission.name;$('quizStep').textContent=`${quizIndex+1} / ${quizQueue.length}`;$('question').textContent=q.q;$('answers').innerHTML='';q.a.forEach((a,i)=>{const b=document.createElement('button');b.textContent=a;b.onclick=()=>answer(b,i);$('answers').appendChild(b)});$('feedback').textContent=''}
function answer(btn,i){const q=quizQueue[quizIndex];[...$('answers').children].forEach(x=>x.disabled=true);const ok=i===q.c;btn.classList.add(ok?'correct':'wrong');if(!ok)$('answers').children[q.c].classList.add('correct');if(ok)quizCorrect++;state.score+=ok?100:30;updateCollection();$('feedback').textContent=ok?'答對了！展品星光 +100':'一起記住正確答案！星光 +30';setTimeout(()=>{quizIndex++;if(quizIndex<quizQueue.length){renderQuizQuestion();return}const m=activeMission;state.mission++;$('quiz').classList.add('hidden');state.phase='play';m.ring.visible=false;m.beam.visible=false;updateObjective();toast(`已收藏：${m.name} · ${quizCorrect}/3 正確`);if(state.mission===world.missions.length)setTimeout(finish,1600)},850)}
function finish(){state.phase='complete';$('finalName').textContent=state.name;$('finalScore').textContent=state.score;$('complete').classList.remove('hidden')}
function start(){state.name=$('playerName').value.trim()||'Explorer';state.phase='play';sfx.unlock();startBgm();$('welcome').classList.add('hidden');$('gameUI').classList.remove('hidden');updateObjective();toast(`歡迎你，${state.name}！`)}
let night=false;$('start').onclick=start;$('playerName').addEventListener('keydown',e=>{if(e.key==='Enter')start()});$('replay').onclick=()=>location.reload();$('interact').onclick=interact;$('sound').onclick=()=>{$('sound').textContent=toggleBgm()?'♩':'♪'};$('time').onclick=()=>{night=!night;$('time').textContent=night?'☾':'☀';scene.background.set(night?0x08172b:0x8ab4c4);scene.fog.color.set(night?0x0b2136:0x89afbd);hemi.intensity=night?1.15:2.2;sun.intensity=night?1.1:3.2;renderer.toneMappingExposure=night?.72:1.05;toast(night?'維港夜景模式':'清晨探索模式')};
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyE')interact();if(e.code==='KeyR'){state.camYaw=0;state.camPitch=.42;toast('鏡頭已面向北方 Camera reset north')}});addEventListener('keyup',e=>keys[e.code]=false);
let dragging=false,lastX=0,lastY=0;renderer.domElement.addEventListener('pointerdown',e=>{if(e.target===$('scene')){dragging=true;lastX=e.clientX;lastY=e.clientY}});addEventListener('pointermove',e=>{if(dragging){state.camYaw-=(e.clientX-lastX)*.006;state.camPitch=Math.max(.12,Math.min(1.12,state.camPitch+(e.clientY-lastY)*.005));lastX=e.clientX;lastY=e.clientY}});addEventListener('pointerup',()=>dragging=false);
const joyEl=$('joystick'),stick=$('stick');function setJoy(e){const r=joyEl.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),l=Math.max(1,Math.hypot(x,y)),d=Math.min(32,l);joy={x:x/l*d/32,y:y/l*d/32};stick.style.transform=`translate(${joy.x*32}px,${joy.y*32}px)`}joyEl.addEventListener('pointerdown',e=>{joyEl.setPointerCapture(e.pointerId);setJoy(e)});joyEl.addEventListener('pointermove',e=>{if(joyEl.hasPointerCapture(e.pointerId))setJoy(e)});function endJoy(){joy={x:0,y:0};stick.style.transform=''}joyEl.addEventListener('pointerup',endJoy);joyEl.addEventListener('pointercancel',endJoy);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const clock=new THREE.Clock();let elapsed=0;
const minimap=$('minimap'),mapCtx=minimap.getContext('2d'),MAP={minX:-88,maxX:88,minZ:-140,maxZ:75};
function mapPoint(x,z){return[(x-MAP.minX)/(MAP.maxX-MAP.minX)*minimap.width,(z-MAP.minZ)/(MAP.maxZ-MAP.minZ)*minimap.height]}
function drawMinimap(){const w=minimap.width,h=minimap.height;mapCtx.clearRect(0,0,w,h);mapCtx.fillStyle='#071a2d';mapCtx.fillRect(0,0,w,h);mapCtx.fillStyle='#0b536c';mapCtx.fillRect(0,h*.84,w,h*.16);mapCtx.strokeStyle='#566775';for(const r of world.roads){mapCtx.lineWidth=Math.max(3,(r.vertical?r.w/(MAP.maxX-MAP.minX)*w:r.d/(MAP.maxZ-MAP.minZ)*h));mapCtx.beginPath();if(r.vertical){const a=mapPoint(r.x,r.z-r.d/2),b=mapPoint(r.x,r.z+r.d/2);mapCtx.moveTo(a[0],a[1]);mapCtx.lineTo(b[0],b[1])}else{const a=mapPoint(r.x-r.w/2,r.z),b=mapPoint(r.x+r.w/2,r.z);mapCtx.moveTo(a[0],a[1]);mapCtx.lineTo(b[0],b[1])}mapCtx.stroke()}world.missions.forEach((m,i)=>{const [x,z]=mapPoint(m.x,m.z);mapCtx.fillStyle=i<state.mission?'#607681':i===state.mission?'#f3c96b':'#6cb9bf';mapCtx.beginPath();mapCtx.arc(x,z,i===state.mission?6:3,0,Math.PI*2);mapCtx.fill()});const [px,pz]=mapPoint(girl.position.x,girl.position.z);mapCtx.save();mapCtx.translate(px,pz);mapCtx.rotate(girl.rotation.y+Math.PI);mapCtx.fillStyle='#fff';mapCtx.beginPath();mapCtx.moveTo(0,-7);mapCtx.lineTo(5,6);mapCtx.lineTo(-5,6);mapCtx.closePath();mapCtx.fill();mapCtx.restore();mapCtx.fillStyle='#f3c96b';mapCtx.font='bold 14px sans-serif';mapCtx.fillText('N',8,18)}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04);elapsed+=dt;let moving=false;if(state.phase==='play'){let x=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+joy.x,z=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+joy.y;const len=Math.hypot(x,z);if(len>.1){x/=len;z/=len;const wx=x,wz=z,spd=9*(elapsed<state.boostUntil?1.55:1);const nx=girl.position.x+wx*spd*dt,nz=girl.position.z+wz*spd*dt;if(!collide(nx,girl.position.z))girl.position.x=nx;if(!collide(girl.position.x,nz))girl.position.z=nz;state.yaw=Math.atan2(wx,wz);girl.rotation.y=state.yaw;moving=true}const target=world.missions[state.mission];state.near=target&&Math.hypot(girl.position.x-target.x,girl.position.z-target.z)<target.r?target:null;state.nearSide=null;if(!state.near){for(const d of sideActivities){if(!d.done&&Math.hypot(girl.position.x-d.x,girl.position.z-d.z)<2.7){state.nearSide=d;break}}}const promptTarget=state.near||state.nearSide;$('interact').classList.toggle('hidden',!promptTarget);if(promptTarget)$('interactText').textContent=promptTarget.prompt;if(target){const angle=Math.atan2(target.x-girl.position.x,-(target.z-girl.position.z))-state.camYaw;$('compassNeedle').style.transform=`rotate(${angle}rad)`}}
  world.vehicles.forEach(v=>{v.group.position[v.axis]+=v.speed*dt;if(v.speed>0&&v.group.position[v.axis]>v.max)v.group.position[v.axis]=v.min;if(v.speed<0&&v.group.position[v.axis]<v.min)v.group.position[v.axis]=v.max;if(state.phase==='play'&&elapsed>state.hitUntil&&Math.hypot(v.group.position.x-girl.position.x,v.group.position.z-girl.position.z)<2.4){state.hitUntil=elapsed+2;state.score=Math.max(0,state.score-10);updateCollection();toast('小心交通！Watch the road · -10 分')}});
  animateGirl(girl,dt,moving?1:0);sideActivities.forEach((d,i)=>{if(d.type==='npc')animateGirl(d.model,dt,0);if(!d.done&&d.model)d.model.rotation.y+=d.type==='npc'?0:dt*.8});if(state.dogFollowing){const dog=sideActivities.find(d=>d.type==='dog'),tx=girl.position.x-Math.sin(girl.rotation.y)*1.8,tz=girl.position.z-Math.cos(girl.rotation.y)*1.8;dog.model.position.x+=(tx-dog.model.position.x)*Math.min(1,dt*4);dog.model.position.z+=(tz-dog.model.position.z)*Math.min(1,dt*4)}world.missions.forEach((m,i)=>{m.ring.rotation.z=elapsed*.25;m.beam.material.opacity=.12+Math.sin(elapsed*2+i)*.05});world.collectibles.forEach((c,i)=>{if(c.taken)return;c.mesh.rotation.y+=dt*2;c.mesh.position.y=(c.type==='gift'?.25:1)+Math.sin(elapsed*3+i)*.18;if(state.phase==='play'&&Math.hypot(c.mesh.position.x-girl.position.x,c.mesh.position.z-girl.position.z)<1.7){c.taken=true;c.mesh.visible=false;state.score+=c.value;sfx.coin();if(c.type==='coin'){state.coins++;toast(`博物館代幣 ${state.coins} · +${c.value} 分`)}else if(c.type==='star'){state.stars++;toast(`香港星光 ${state.stars} · +${c.value} 分`)}else{state.coins+=5;toast(`神秘禮物！+${c.value} 分`)}updateCollection()}});drawMinimap();
  const dist=innerWidth<760?14:12,height=Math.sin(state.camPitch)*dist+2.2,horiz=Math.cos(state.camPitch)*dist;const desired=new THREE.Vector3(girl.position.x+Math.sin(state.camYaw)*horiz,height,girl.position.z+Math.cos(state.camYaw)*horiz);camera.position.lerp(desired,1-Math.pow(.001,dt));camera.lookAt(girl.position.x,2.3,girl.position.z);renderer.render(scene,camera)}
window.__dgV2={girl,state,camera,world};updateObjective();loop();setTimeout(()=>{$('loading').style.opacity=0;setTimeout(()=>$('loading').remove(),500)},650);
