// ============================================================
// EASY bank (P1–P2) — 200 questions, 50 per category.
// Level: 2-digit add/subtract with carrying, early times tables,
// time, money, shapes; basic grammar & vocabulary.
// ============================================================
export const EASY = [
  // ---- math ----
  { cat: 'math', q: '23 + 18 = ?', a: ['39', '41', '43', '31'], c: 1 },
  { cat: 'math', q: '35 − 17 = ?', a: ['18', '22', '12', '28'], c: 0 },
  { cat: 'math', q: '46 + 29 = ?', a: ['65', '74', '75', '85'], c: 2 },
  { cat: 'math', q: '60 − 24 = ?', a: ['44', '36', '46', '34'], c: 1 },
  { cat: 'math', q: '17 + 8 = ?', a: ['24', '25', '26', '23'], c: 1 },
  { cat: 'math', q: '42 − 15 = ?', a: ['27', '37', '23', '33'], c: 0 },
  { cat: 'math', q: '8 × 2 = ?', a: ['14', '16', '18', '12'], c: 1 },
  { cat: 'math', q: '5 × 4 = ?', a: ['9', '15', '20', '25'], c: 2 },
  { cat: 'math', q: '10 × 7 = ?', a: ['17', '70', '77', '107'], c: 1 },
  { cat: 'math', q: '18 ÷ 2 = ?', a: ['6', '8', '9', '16'], c: 2 },
  { cat: 'math', q: '3、6、9、12，下一個數是？', a: ['13', '14', '15', '18'], c: 2 },
  { cat: 'math', q: '5、10、15、20，下一個數是？', a: ['21', '25', '30', '40'], c: 1 },
  { cat: 'math', q: '100 − 45 = ?', a: ['45', '55', '65', '54'], c: 1 },
  { cat: 'math', q: '37 + 37 = ?', a: ['64', '74', '77', '84'], c: 1 },
  { cat: 'math', q: '用 $20 買 $12 的文具，找回多少錢？', a: ['$6', '$8', '$10', '$12'], c: 1 },
  { cat: 'math', q: '1 星期有 7 日，2 星期有多少日？', a: ['9 日', '12 日', '14 日', '17 日'], c: 2 },
  { cat: 'math', q: '半小時等於多少分鐘？', a: ['15 分鐘', '30 分鐘', '45 分鐘', '60 分鐘'], c: 1 },
  { cat: 'math', q: '時針指住 3，分針指住 12，是幾點？', a: ['12 點', '3 點正', '3 點半', '6 點'], c: 1 },
  { cat: 'math', q: '哪一個是雙數？', a: ['7', '9', '14', '21'], c: 2 },
  { cat: 'math', q: '哪一個是單數？', a: ['8', '13', '20', '16'], c: 1 },
  { cat: 'math', q: '一個長方形有多少隻角？', a: ['2', '3', '4', '5'], c: 2 },
  { cat: 'math', q: '一個三角形有多少條邊？', a: ['2', '3', '4', '5'], c: 1 },
  { cat: 'math', q: '比 50 大 10 的數是？', a: ['40', '51', '60', '65'], c: 2 },
  { cat: 'math', q: '9 + 9 + 9 = ?', a: ['18', '27', '28', '36'], c: 1 },
  { cat: 'math', q: '2 個十加 3 個一是多少？', a: ['5', '23', '32', '203'], c: 1 },
  { cat: 'math', q: '一條繩長 30 厘米，剪走 12 厘米，剩多少？', a: ['18 厘米', '22 厘米', '16 厘米', '42 厘米'], c: 0 },
  { cat: 'math', q: '哪一組數由小到大排列？', a: ['31, 13, 3', '13, 3, 31', '3, 13, 31', '31, 3, 13'], c: 2 },
  { cat: 'math', q: '媽媽買了 6 隻蛋，再買 6 隻，共有多少隻？', a: ['10', '12', '14', '16'], c: 1 },
  { cat: 'math', q: '$1 + $2 + $5 = ?', a: ['$7', '$8', '$9', '$10'], c: 1 },
  { cat: 'math', q: '10 減去多少等於 4？', a: ['4', '5', '6', '7'], c: 2 },
  { cat: 'math', q: '28 + 16 = ?', a: ['34', '42', '44', '46'], c: 2 },
  { cat: 'math', q: '53 − 28 = ?', a: ['25', '35', '23', '31'], c: 0 },
  { cat: 'math', q: '34 + 27 = ?', a: ['51', '59', '61', '63'], c: 2 },
  { cat: 'math', q: '70 − 36 = ?', a: ['34', '36', '44', '46'], c: 0 },
  { cat: 'math', q: '6 × 2 = ?', a: ['8', '10', '12', '14'], c: 2 },
  { cat: 'math', q: '9 × 5 = ?', a: ['40', '45', '50', '54'], c: 1 },
  { cat: 'math', q: '10 × 10 = ?', a: ['20', '100', '110', '1000'], c: 1 },
  { cat: 'math', q: '14 ÷ 2 = ?', a: ['6', '7', '8', '12'], c: 1 },
  { cat: 'math', q: '4、8、12、16，下一個數是？', a: ['18', '20', '22', '24'], c: 1 },
  { cat: 'math', q: '10、20、30，下一個數是？', a: ['35', '40', '50', '60'], c: 1 },
  { cat: 'math', q: '一支雪條 $5，買 2 支要多少錢？', a: ['$7', '$10', '$12', '$15'], c: 1 },
  { cat: 'math', q: '24 粒糖分成兩份，每份有幾多粒？', a: ['10', '12', '14', '22'], c: 1 },
  { cat: 'math', q: '6 點正的時候，分針指住邊個數字？', a: ['3', '6', '9', '12'], c: 3 },
  { cat: 'math', q: '一日有幾多個小時？', a: ['12', '20', '24', '30'], c: 2 },
  { cat: 'math', q: '50 + 50 = ?', a: ['90', '100', '110', '105'], c: 1 },
  { cat: 'math', q: '81 − 9 = ?', a: ['70', '72', '74', '78'], c: 1 },
  { cat: 'math', q: '7 + 7 + 7 = ?', a: ['14', '21', '24', '28'], c: 1 },
  { cat: 'math', q: '哪一個數最接近 30？', a: ['24', '29', '35', '39'], c: 1 },
  { cat: 'math', q: '3 個十加 5 個一是多少？', a: ['8', '35', '53', '305'], c: 1 },
  { cat: 'math', q: '16 減去多少等於 9？', a: ['5', '6', '7', '8'], c: 2 },

  // ---- english ----
  { cat: 'english', q: '"I ___ a student."', a: ['am', 'is', 'are', 'be'], c: 0 },
  { cat: 'english', q: '"She ___ my sister."', a: ['am', 'is', 'are', 'be'], c: 1 },
  { cat: 'english', q: '"They ___ happy."', a: ['am', 'is', 'are', 'be'], c: 2 },
  { cat: 'english', q: 'The plural of "box" is…', a: ['boxs', 'boxes', 'boxies', 'box'], c: 1 },
  { cat: 'english', q: 'The plural of "cat" is…', a: ['cats', 'cates', 'caties', 'cat'], c: 0 },
  { cat: 'english', q: '"This is ___ egg."', a: ['a', 'an', 'two', 'many'], c: 1 },
  { cat: 'english', q: 'The opposite of "big" is…', a: ['tall', 'small', 'fat', 'long'], c: 1 },
  { cat: 'english', q: 'The opposite of "hot" is…', a: ['warm', 'cold', 'wet', 'dry'], c: 1 },
  { cat: 'english', q: 'The opposite of "fast" is…', a: ['quick', 'slow', 'late', 'far'], c: 1 },
  { cat: 'english', q: 'Which day comes after Monday?', a: ['Sunday', 'Tuesday', 'Friday', 'Saturday'], c: 1 },
  { cat: 'english', q: 'The first month of the year is…', a: ['December', 'January', 'February', 'March'], c: 1 },
  { cat: 'english', q: 'We see with our ___.', a: ['ears', 'eyes', 'nose', 'mouth'], c: 1 },
  { cat: 'english', q: 'Which one is a fruit?', a: ['Chair', 'Apple', 'Car', 'Book'], c: 1 },
  { cat: 'english', q: 'Which animal can fly?', a: ['Fish', 'Bird', 'Dog', 'Pig'], c: 1 },
  { cat: 'english', q: 'Which one can swim?', a: ['Fish', 'Cat', 'Bird', 'Hen'], c: 0 },
  { cat: 'english', q: 'Which word rhymes with "cat"?', a: ['cut', 'hat', 'cot', 'kite'], c: 1 },
  { cat: 'english', q: '"___ name is Mary. She is my friend."', a: ['Her', 'His', 'My', 'Him'], c: 0 },
  { cat: 'english', q: 'How many days are there in a week?', a: ['Five', 'Six', 'Seven', 'Eight'], c: 2 },
  { cat: 'english', q: '"I go to school ___ bus."', a: ['on', 'by', 'in', 'at'], c: 1 },
  { cat: 'english', q: 'A baby dog is called a…', a: ['kitten', 'puppy', 'chick', 'cub'], c: 1 },
  { cat: 'english', q: '"Two ___ are on the table."', a: ['book', 'books', 'bookes', 'a book'], c: 1 },
  { cat: 'english', q: 'Which word is a number?', a: ['Nice', 'Nine', 'Name', 'Nose'], c: 1 },
  { cat: 'english', q: 'Strawberries are ___.', a: ['blue', 'red', 'black', 'purple'], c: 1 },
  { cat: 'english', q: '"Open the door, ___."', a: ['sorry', 'please', 'yes', 'bye'], c: 1 },
  { cat: 'english', q: 'Which one do we use at school?', a: ['Pillow', 'Pencil', 'Pan', 'Pyjamas'], c: 1 },
  { cat: 'english', q: '"I wash my ___ before dinner."', a: ['hands', 'shoes', 'bag', 'hair'], c: 0 },
  { cat: 'english', q: '"How ___ are you?" "I am seven."', a: ['old', 'tall', 'many', 'much'], c: 0 },
  { cat: 'english', q: 'Which word means 書?', a: ['Bag', 'Book', 'Ball', 'Bed'], c: 1 },
  { cat: 'english', q: '"___ morning, Miss Chan!"', a: ['Nice', 'Good', 'Well', 'Fine'], c: 1 },
  { cat: 'english', q: '"I have two ___."', a: ['hand', 'hands', 'handes', 'a hand'], c: 1 },
  { cat: 'english', q: 'The opposite of "happy" is…', a: ['glad', 'sad', 'fun', 'nice'], c: 1 },
  { cat: 'english', q: '"He ___ a dog."', a: ['have', 'has', 'is', 'are'], c: 1 },
  { cat: 'english', q: '"We ___ in the park."', a: ['plays', 'play', 'playing', 'is play'], c: 1 },
  { cat: 'english', q: 'The plural of "bus" is…', a: ['bus', 'buss', 'buses', 'busies'], c: 2 },
  { cat: 'english', q: '"I eat ___ orange every day."', a: ['a', 'an', 'two', 'much'], c: 1 },
  { cat: 'english', q: 'Which word rhymes with "dog"?', a: ['dig', 'log', 'duck', 'door'], c: 1 },
  { cat: 'english', q: 'Which one is a vegetable?', a: ['Carrot', 'Cake', 'Candy', 'Cup'], c: 0 },
  { cat: 'english', q: '"I brush my ___ every night."', a: ['shoes', 'teeth', 'books', 'toys'], c: 1 },
  { cat: 'english', q: 'Which day comes before Sunday?', a: ['Monday', 'Friday', 'Saturday', 'Tuesday'], c: 2 },
  { cat: 'english', q: '"___ is your name?"', a: ['Who', 'What', 'Where', 'When'], c: 1 },
  { cat: 'english', q: 'A baby cat is called a…', a: ['puppy', 'kitten', 'chick', 'lamb'], c: 1 },
  { cat: 'english', q: '"The cat is ___ the box."', a: ['in', 'of', 'to', 'and'], c: 0 },
  { cat: 'english', q: 'Which one is cold?', a: ['Fire', 'Ice', 'Sun', 'Soup'], c: 1 },
  { cat: 'english', q: 'Which number comes after nine?', a: ['Eight', 'Ten', 'Seven', 'Six'], c: 1 },
  { cat: 'english', q: '"She wears a red ___."', a: ['dress', 'run', 'eat', 'happy'], c: 0 },
  { cat: 'english', q: 'We hear with our ___.', a: ['eyes', 'ears', 'hands', 'feet'], c: 1 },
  { cat: 'english', q: 'The opposite of "open" is…', a: ['close', 'out', 'up', 'big'], c: 0 },
  { cat: 'english', q: '"I am ___ years old."', a: ['eight', 'apple', 'egg', 'eat'], c: 0 },
  { cat: 'english', q: 'Which animal can hop?', a: ['Fish', 'Rabbit', 'Snake', 'Snail'], c: 1 },
  { cat: 'english', q: '"Happy ___ to you!"', a: ['Birthday', 'Bedtime', 'Bath', 'Book'], c: 0 },

  // ---- chinese ----
  { cat: 'chinese', q: '「大」的相反詞是？', a: ['高', '小', '多', '長'], c: 1 },
  { cat: 'chinese', q: '一（　）狗 — 應填哪個量詞？', a: ['本', '隻', '張', '架'], c: 1 },
  { cat: 'chinese', q: '「日」+「月」合起來是哪個字？', a: ['明', '晶', '昌', '朋'], c: 0 },
  { cat: 'chinese', q: '「上」的相反是？', a: ['左', '下', '中', '前'], c: 1 },
  { cat: 'chinese', q: '哪個字是顏色？', a: ['跑', '紅', '吃', '看'], c: 1 },
  { cat: 'chinese', q: '「爸爸的媽媽」我們叫她？', a: ['姨媽', '祖母', '姑姐', '舅母'], c: 1 },
  { cat: 'chinese', q: '「木」字有多少筆畫？', a: ['3', '4', '5', '6'], c: 1 },
  { cat: 'chinese', q: '一（　）書 — 應填哪個量詞？', a: ['隻', '本', '條', '輛'], c: 1 },
  { cat: 'chinese', q: '一（　）花 — 應填哪個量詞？', a: ['朵', '隻', '架', '間'], c: 0 },
  { cat: 'chinese', q: '「人」字有多少筆畫？', a: ['1', '2', '3', '4'], c: 1 },
  { cat: 'chinese', q: '「白天」的相反是？', a: ['早上', '黑夜', '中午', '下午'], c: 1 },
  { cat: 'chinese', q: '「快」的相反詞是？', a: ['急', '慢', '早', '遲'], c: 1 },
  { cat: 'chinese', q: '一（　）魚 — 應填哪個量詞？', a: ['條', '張', '本', '把'], c: 0 },
  { cat: 'chinese', q: '「出」的相反詞是？', a: ['入', '去', '走', '回'], c: 0 },
  { cat: 'chinese', q: '春、夏、秋、冬，哪個季節最冷？', a: ['春', '夏', '秋', '冬'], c: 3 },
  { cat: 'chinese', q: '「笑」的相反詞是？', a: ['唱', '哭', '叫', '講'], c: 1 },
  { cat: 'chinese', q: '太陽從哪一邊升起？', a: ['東', '南', '西', '北'], c: 0 },
  { cat: 'chinese', q: '「水」字有多少筆畫？', a: ['3', '4', '5', '6'], c: 1 },
  { cat: 'chinese', q: '哪個字和「手」的動作有關？', a: ['看', '拍', '聽', '行'], c: 1 },
  { cat: 'chinese', q: '「高」的相反詞是？', a: ['大', '矮', '長', '肥'], c: 1 },
  { cat: 'chinese', q: '「多」的相反詞是？', a: ['大', '少', '高', '長'], c: 1 },
  { cat: 'chinese', q: '「天」字有多少筆畫？', a: ['3', '4', '5', '6'], c: 1 },
  { cat: 'chinese', q: '「左」的相反是？', a: ['上', '右', '前', '後'], c: 1 },
  { cat: 'chinese', q: '「開」的相反詞是？', a: ['閂', '關', '推', '拉'], c: 1 },
  { cat: 'chinese', q: '一（　）車 — 應填哪個量詞？', a: ['隻', '輛', '本', '條'], c: 1 },
  { cat: 'chinese', q: '「買」的相反詞是？', a: ['賣', '送', '借', '換'], c: 0 },
  { cat: 'chinese', q: '「先」的相反詞是？', a: ['前', '後', '早', '快'], c: 1 },
  { cat: 'chinese', q: '「明」字的部首是？', a: ['日', '月', '門', '木'], c: 0 },
  { cat: 'chinese', q: '「媽」字的部首是？', a: ['馬', '女', '口', '心'], c: 1 },
  { cat: 'chinese', q: '「一閃一閃」通常用來形容？', a: ['星星', '大樹', '石頭', '桌子'], c: 0 },
  { cat: 'chinese', q: '「來」的相反詞是？', a: ['去', '到', '回', '入'], c: 0 },
  { cat: 'chinese', q: '一（　）牛 — 應填哪個量詞？', a: ['頭', '張', '本', '朵'], c: 0 },
  { cat: 'chinese', q: '兩個「木」字合起來是哪個字？', a: ['森', '林', '杜', '本'], c: 1 },
  { cat: 'chinese', q: '「火」字有多少筆畫？', a: ['3', '4', '5', '6'], c: 1 },
  { cat: 'chinese', q: '「大」字加一點是哪個字？', a: ['太', '天', '木', '夫'], c: 0 },
  { cat: 'chinese', q: '「前」的相反是？', a: ['上', '後', '左', '內'], c: 1 },
  { cat: 'chinese', q: '哪個字是動物？', a: ['魚', '書', '山', '門'], c: 0 },
  { cat: 'chinese', q: '哪個字代表「太陽」？', a: ['月', '日', '星', '雲'], c: 1 },
  { cat: 'chinese', q: '一（　）褲 — 應填哪個量詞？', a: ['條', '隻', '本', '粒'], c: 0 },
  { cat: 'chinese', q: '「東」的相反方向是？', a: ['南', '西', '北', '中'], c: 1 },
  { cat: 'chinese', q: '老師通常在哪裡教書？', a: ['醫院', '學校', '機場', '酒樓'], c: 1 },
  { cat: 'chinese', q: '「媽媽的姊妹」我們叫她？', a: ['姑姐', '姨媽', '嬸嬸', '舅母'], c: 1 },
  { cat: 'chinese', q: '「早」的相反詞是？', a: ['晚', '快', '先', '日'], c: 0 },
  { cat: 'chinese', q: '「乾」的相反詞是？', a: ['濕', '清', '淨', '暖'], c: 0 },
  { cat: 'chinese', q: '哪個詞語形容下雨的聲音？', a: ['滴滴答答', '汪汪', '喵喵', '哈哈'], c: 0 },
  { cat: 'chinese', q: '「王」字加一點是哪個字？', a: ['主', '玉', '全', '金'], c: 1 },
  { cat: 'chinese', q: '「口」字有多少筆畫？', a: ['2', '3', '4', '5'], c: 1 },
  { cat: 'chinese', q: '「胖」的相反詞是？', a: ['高', '瘦', '細', '輕'], c: 1 },
  { cat: 'chinese', q: '一（　）糖 — 應填哪個量詞？', a: ['粒', '條', '張', '架'], c: 0 },
  { cat: 'chinese', q: '哭的時候會流出什麼？', a: ['汗水', '眼淚', '雨水', '口水'], c: 1 },

  // ---- general ----
  { cat: 'general', q: '紅綠燈中哪個顏色代表「停」？', a: ['綠色', '紅色', '黃色', '藍色'], c: 1 },
  { cat: 'general', q: '香港市區的士是什麼顏色？', a: ['黃色', '紅色', '綠色', '藍色'], c: 1 },
  { cat: 'general', q: '過馬路時應該走？', a: ['馬路中間', '斑馬線', '車路', '欄杆'], c: 1 },
  { cat: 'general', q: '香港人搭車購物常用什麼卡？', a: ['圖書卡', '八達通', '生日卡', '貼紙卡'], c: 1 },
  { cat: 'general', q: '一年有多少個月？', a: ['10', '11', '12', '13'], c: 2 },
  { cat: 'general', q: '下雨天出門應該帶什麼？', a: ['風箏', '雨傘', '太陽眼鏡', '滑板'], c: 1 },
  { cat: 'general', q: '天星小輪在哪裡行駛？', a: ['天空', '海上', '馬路', '山上'], c: 1 },
  { cat: 'general', q: '護士通常在哪裡工作？', a: ['學校', '醫院', '機場', '街市'], c: 1 },
  { cat: 'general', q: '哪一個是交通工具？', a: ['枱', '巴士', '書包', '電視'], c: 1 },
  { cat: 'general', q: '晚上抬頭會見到什麼？', a: ['太陽', '月亮', '彩虹', '白雲'], c: 1 },
  { cat: 'general', q: '消防員救火時開什麼車？', a: ['救護車', '消防車', '校巴', '貨車'], c: 1 },
  { cat: 'general', q: '我們用什麼器官聽聲音？', a: ['眼睛', '耳朵', '鼻子', '嘴巴'], c: 1 },
  { cat: 'general', q: '哪種動物的頸最長？', a: ['大象', '長頸鹿', '獅子', '熊貓'], c: 1 },
  { cat: 'general', q: '香港的雙層巴士有多少層？', a: ['1 層', '2 層', '3 層', '4 層'], c: 1 },
  { cat: 'general', q: '尖沙咀有一個著名的高塔叫？', a: ['鐘樓', '燈塔', '水塔', '炮台'], c: 0 },
  { cat: 'general', q: '報告香港天氣的機構叫？', a: ['天文台', '消防局', '郵政局', '水務署'], c: 0 },
  { cat: 'general', q: '維多利亞港隔開九龍和哪裡？', a: ['新界', '香港島', '大嶼山', '澳門'], c: 1 },
  { cat: 'general', q: '落大雨之前，天上多數有很多？', a: ['星星', '烏雲', '彩虹', '風箏'], c: 1 },
  { cat: 'general', q: '在圖書館裡應該？', a: ['大聲唱歌', '保持安靜', '跑來跑去', '吃零食'], c: 1 },
  { cat: 'general', q: '過馬路前應該先？', a: ['閉上眼睛', '望清楚左右', '跑得快些', '玩手機'], c: 1 },
  { cat: 'general', q: '香港的夏天天氣是？', a: ['又熱又濕', '經常落雪', '非常乾凍', '成日結冰'], c: 0 },
  { cat: 'general', q: '中秋節小朋友會玩什麼？', a: ['燈籠', '風箏', '滑梯', '雪人'], c: 0 },
  { cat: 'general', q: '農曆新年常說的祝賀語是？', a: ['節日快樂', '恭喜發財', '中秋快樂', '生日快樂'], c: 1 },
  { cat: 'general', q: '香港小學生返學要穿什麼？', a: ['泳衣', '校服', '睡衣', '戲服'], c: 1 },
  { cat: 'general', q: '12 月 25 日是什麼節日？', a: ['中秋節', '聖誕節', '復活節', '端午節'], c: 1 },
  { cat: 'general', q: '香港的救護車主要是什麼顏色？', a: ['黑色', '白色', '紫色', '啡色'], c: 1 },
  { cat: 'general', q: '緊急求助應該打哪個電話號碼？', a: ['111', '999', '888', '123'], c: 1 },
  { cat: 'general', q: '食飯之前應該先？', a: ['睇電視', '洗手', '瞓覺', '跑步'], c: 1 },
  { cat: 'general', q: '邊個節日會收利是？', a: ['中秋節', '農曆新年', '復活節', '萬聖節'], c: 1 },
  { cat: 'general', q: '中秋節我們會吃什麼？', a: ['湯圓', '月餅', '糭', '年糕'], c: 1 },
  { cat: 'general', q: '香港區旗是什麼顏色配白花？', a: ['藍色', '紅色', '綠色', '黃色'], c: 1 },
  { cat: 'general', q: '邊種動物會「汪汪」叫？', a: ['貓', '狗', '雞', '羊'], c: 1 },
  { cat: 'general', q: '月亮通常在什麼時候見到？', a: ['中午', '晚上', '朝早', '下午茶時間'], c: 1 },
  { cat: 'general', q: '港鐵列車行駛在什麼上面？', a: ['馬路', '路軌', '海面', '草地'], c: 1 },
  { cat: 'general', q: '香港的冬天通常會唔會落雪？', a: ['日日落雪', '通常不會', '成個月落', '同北極一樣'], c: 1 },
  { cat: 'general', q: '蜜蜂採什麼來造蜜？', a: ['樹葉', '花蜜', '泥土', '石頭'], c: 1 },
  { cat: 'general', q: '牛奶是來自哪種動物？', a: ['雞', '牛', '魚', '蛇'], c: 1 },
  { cat: 'general', q: '雞蛋是哪種動物生的？', a: ['鴨', '雞', '貓', '牛'], c: 1 },
  { cat: 'general', q: '搭巴士上車前應該？', a: ['爭先恐後', '排隊等候', '推開別人', '大叫大嚷'], c: 1 },
  { cat: 'general', q: '紅綠燈的黃燈代表？', a: ['加速衝過', '準備停下', '可以跳舞', '熄燈休息'], c: 1 },
  { cat: 'general', q: '端午節我們會吃什麼？', a: ['月餅', '糭', '湯圓', '蛋糕'], c: 1 },
  { cat: 'general', q: '聖誕老人穿什麼顏色的衫？', a: ['藍色', '紅色', '綠色', '黑色'], c: 1 },
  { cat: 'general', q: '郵差叔叔負責送什麼？', a: ['外賣', '信件', '汽水', '玩具'], c: 1 },
  { cat: 'general', q: '上太平山頂可以搭什麼？', a: ['山頂纜車', '天星小輪', '電車', '飛機'], c: 0 },
  { cat: 'general', q: '去圖書館借書要用什麼？', a: ['八達通', '圖書證', '車票', '戲票'], c: 1 },
  { cat: 'general', q: '牙痛應該去看哪位？', a: ['獸醫', '牙醫', '消防員', '廚師'], c: 1 },
  { cat: 'general', q: '農曆新年屋企會貼什麼？', a: ['聖誕卡', '揮春', '海報', '地圖'], c: 1 },
  { cat: 'general', q: '港鐵車廂內可以飲食嗎？', a: ['可以', '不可以', '星期日先可以', '飲水以外都得'], c: 1 },
  { cat: 'general', q: '哪一樣是植物？', a: ['大樹', '石頭', '巴士', '電話'], c: 0 },
  { cat: 'general', q: '落街玩之前應該話俾邊個知？', a: ['無需通知', '家長', '陌生人', '寵物'], c: 1 },
];
