// ============================================================
// HARD bank (P5–P6) — 200 questions, 50 per category.
// Level: percentages, ratio, algebra, speed, volume; passive
// voice & conditionals; classical allusions & poetry.
// ============================================================
export const HARD = [
  // ---- math ----
  { cat: 'math', q: '1/2 + 1/4 = ?', a: ['2/6', '3/4', '1/6', '2/4'], c: 1 },
  { cat: 'math', q: '50 的 20% 是多少？', a: ['5', '10', '15', '20'], c: 1 },
  { cat: 'math', q: '3.6 + 2.75 = ?', a: ['5.35', '6.35', '6.45', '5.45'], c: 1 },
  { cat: 'math', q: '2 + 3 × 4 = ?', a: ['20', '14', '24', '12'], c: 1 },
  { cat: 'math', q: '4、6、8 三個數的平均數是？', a: ['5', '6', '7', '8'], c: 1 },
  { cat: 'math', q: '三角形底 10cm、高 6cm，面積是？', a: ['16 cm²', '30 cm²', '60 cm²', '36 cm²'], c: 1 },
  { cat: 'math', q: '4 和 6 的最小公倍數是？', a: ['10', '12', '24', '8'], c: 1 },
  { cat: 'math', q: '0.25 等於幾分之幾？', a: ['1/2', '1/4', '1/5', '2/5'], c: 1 },
  { cat: 'math', q: '一個數的 3 倍加 7 等於 22，這個數是？', a: ['4', '5', '6', '7'], c: 1 },
  { cat: 'math', q: '圓周率 π 大約等於？', a: ['2.14', '3.14', '4.13', '3.41'], c: 1 },
  { cat: 'math', q: '1000 − 387 = ?', a: ['713', '623', '613', '603'], c: 2 },
  { cat: 'math', q: '哪一個是質數？', a: ['15', '21', '17', '27'], c: 2 },
  { cat: 'math', q: '正方形面積 49 cm²，邊長是？', a: ['6 cm', '7 cm', '8 cm', '9 cm'], c: 1 },
  { cat: 'math', q: '3/5 等於百分之幾？', a: ['35%', '60%', '53%', '65%'], c: 1 },
  { cat: 'math', q: '3/4 ÷ 1/2 = ?', a: ['3/8', '1 1/2', '2/3', '1 1/4'], c: 1 },
  { cat: 'math', q: '2.4 × 1.5 = ?', a: ['3.6', '3.9', '2.9', '4.6'], c: 0 },
  { cat: 'math', q: '240 的 15% 是多少？', a: ['24', '30', '36', '45'], c: 2 },
  { cat: 'math', q: '行 90 公里用了 1.5 小時，平均時速是？', a: ['45 km/h', '60 km/h', '75 km/h', '135 km/h'], c: 1 },
  { cat: 'math', q: '男女比例是 2:3，男生有 12 人，女生有多少人？', a: ['8', '15', '18', '24'], c: 2 },
  { cat: 'math', q: '36 和 48 的最大公因數是？', a: ['6', '8', '12', '16'], c: 2 },
  { cat: 'math', q: '半徑 7cm 的圓，圓周大約是？(π≈22/7)', a: ['22 cm', '44 cm', '154 cm', '49 cm'], c: 1 },
  { cat: 'math', q: '5x − 8 = 27，x = ?', a: ['5', '6', '7', '8'], c: 2 },
  { cat: 'math', q: '正方體邊長 4cm，體積是？', a: ['16 cm³', '48 cm³', '64 cm³', '96 cm³'], c: 2 },
  { cat: 'math', q: '連續 5 個雙數的和是 60，中間那個數是？', a: ['10', '12', '14', '16'], c: 1 },
  { cat: 'math', q: '原價 $250 的裙打八折，售價是？', a: ['$180', '$200', '$220', '$230'], c: 1 },
  { cat: 'math', q: '7.2 ÷ 0.9 = ?', a: ['0.8', '8', '80', '7.9'], c: 1 },
  { cat: 'math', q: '三角形兩隻角是 65° 和 48°，第三隻角是？', a: ['57°', '67°', '77°', '113°'], c: 1 },
  { cat: 'math', q: '甲數是乙數的 3 倍，兩數之和是 48，乙數是？', a: ['12', '16', '24', '36'], c: 0 },
  { cat: 'math', q: '√81 = ?', a: ['8', '9', '18', '40.5'], c: 1 },
  { cat: 'math', q: '長方體共有多少條棱？', a: ['8', '10', '12', '16'], c: 2 },
  { cat: 'math', q: '2/3 × 3/4 = ?', a: ['1/2', '5/7', '6/7', '2/4'], c: 0 },
  { cat: 'math', q: '4.5 ÷ 1.5 = ?', a: ['2', '3', '4', '3.5'], c: 1 },
  { cat: 'math', q: '125 × 8 = ?', a: ['900', '1000', '1100', '1200'], c: 1 },
  { cat: 'math', q: '一件衫加價 10% 後賣 $220，原價是？', a: ['$198', '$200', '$210', '$242'], c: 1 },
  { cat: 'math', q: '80、85、90、95 四個數的平均數是？', a: ['85', '87.5', '88', '90'], c: 1 },
  { cat: 'math', q: '12 共有多少個因數？', a: ['4', '5', '6', '8'], c: 2 },
  { cat: 'math', q: '1.25 等於哪個分數？', a: ['5/4', '4/5', '1/4', '12/5'], c: 0 },
  { cat: 'math', q: '連續三個單數的和是 45，最大那個是？', a: ['15', '17', '19', '21'], c: 1 },
  { cat: 'math', q: '圓半徑 5cm，面積大約是？(π≈3.14)', a: ['31.4 cm²', '78.5 cm²', '15.7 cm²', '25 cm²'], c: 1 },
  { cat: 'math', q: '2 : 5 = 8 : ?', a: ['11', '16', '20', '40'], c: 2 },
  { cat: 'math', q: '3 小時行 12 公里，行 20 公里要幾多小時？', a: ['4', '5', '6', '8'], c: 1 },
  { cat: 'math', q: '0.07 × 100 = ?', a: ['0.7', '7', '70', '700'], c: 1 },
  { cat: 'math', q: '3x − 5 = 16，x = ?', a: ['5', '6', '7', '8'], c: 2 },
  { cat: 'math', q: '長方體長 5cm、闊 4cm、高 3cm，體積是？', a: ['12 cm³', '47 cm³', '60 cm³', '94 cm³'], c: 2 },
  { cat: 'math', q: '30 的 40% 是多少？', a: ['10', '12', '14', '18'], c: 1 },
  { cat: 'math', q: '6 和 8 的最小公倍數是？', a: ['14', '24', '48', '12'], c: 1 },
  { cat: 'math', q: '7² − 3² = ?', a: ['16', '40', '44', '58'], c: 1 },
  { cat: 'math', q: '540 ÷ 12 = ?', a: ['40', '45', '48', '54'], c: 1 },
  { cat: 'math', q: '一個角和它的餘角相等，這個角是？', a: ['30°', '45°', '60°', '90°'], c: 1 },
  { cat: 'math', q: '1, 4, 9, 16, 25, … 下一個數是？', a: ['30', '36', '49', '50'], c: 1 },

  // ---- english ----
  { cat: 'english', q: 'The past participle of "write" is…', a: ['wrote', 'written', 'writed', 'writing'], c: 1 },
  { cat: 'english', q: '"If it rains, we ___ stay home."', a: ['will', 'would', 'did', 'were'], c: 0 },
  { cat: 'english', q: 'A synonym of "important" is…', a: ['useless', 'essential', 'simple', 'common'], c: 1 },
  { cat: 'english', q: '"English ___ all over the world."', a: ['speaks', 'is spoken', 'is speaking', 'spoke'], c: 1 },
  { cat: 'english', q: 'Which idiom means "very easy"?', a: ['raining cats and dogs', 'a piece of cake', 'under the weather', 'break a leg'], c: 1 },
  { cat: 'english', q: 'The opposite of "ancient" is…', a: ['old', 'modern', 'antique', 'aged'], c: 1 },
  { cat: 'english', q: '"Neither Tom ___ Mary likes durian."', a: ['or', 'nor', 'and', 'but'], c: 1 },
  { cat: 'english', q: 'Which word is an adverb?', a: ['quick', 'quickly', 'quickness', 'quicken'], c: 1 },
  { cat: 'english', q: '"She has lived here ___ 2010."', a: ['for', 'since', 'from', 'at'], c: 1 },
  { cat: 'english', q: '"I look forward to ___ you."', a: ['see', 'seeing', 'saw', 'seen'], c: 1 },
  { cat: 'english', q: 'Which word means "happening once a year"?', a: ['daily', 'annual', 'monthly', 'weekly'], c: 1 },
  { cat: 'english', q: '"He asked me where ___."', a: ['do I live', 'I lived', 'am I living', 'do I lived'], c: 1 },
  { cat: 'english', q: 'The antonym of "generous" is…', a: ['kind', 'stingy', 'wealthy', 'giving'], c: 1 },
  { cat: 'english', q: '"Raining cats and dogs" means…', a: ['pets falling', 'raining heavily', 'sunny weather', 'a light shower'], c: 1 },
  { cat: 'english', q: '"The match was called off" means it was…', a: ['won', 'cancelled', 'started', 'shortened'], c: 1 },
  { cat: 'english', q: '"___ of the students has a dictionary."', a: ['All', 'Each', 'Both', 'Many'], c: 1 },
  { cat: 'english', q: 'Which is spelled correctly?', a: ['recieve', 'receive', 'receeve', 'riceive'], c: 1 },
  { cat: 'english', q: '"By the time we arrived, the show ___."', a: ['starts', 'had started', 'is starting', 'start'], c: 1 },
  { cat: 'english', q: 'She said she ___ tired.', a: ['is', 'was', 'are', 'be'], c: 1 },
  { cat: 'english', q: '"Despite ___ hard, he failed the test."', a: ['work', 'worked', 'working', 'works'], c: 2 },
  { cat: 'english', q: '"Give up" means…', a: ['to lift', 'to quit', 'to donate', 'to climb'], c: 1 },
  { cat: 'english', q: '"The book, ___ I read last week, was great."', a: ['who', 'which', 'where', 'whom'], c: 1 },
  { cat: 'english', q: 'A synonym of "enormous" is…', a: ['tiny', 'gigantic', 'narrow', 'average'], c: 1 },
  { cat: 'english', q: '"I wish I ___ taller."', a: ['am', 'is', 'were', 'be'], c: 2 },
  { cat: 'english', q: 'The prefix "im-" in "impossible" means…', a: ['very', 'not', 'again', 'before'], c: 1 },
  { cat: 'english', q: 'A group of lions is called a…', a: ['herd', 'pride', 'flock', 'pack'], c: 1 },
  { cat: 'english', q: '"He is allergic ___ peanuts."', a: ['of', 'to', 'with', 'at'], c: 1 },
  { cat: 'english', q: 'The antonym of "transparent" is…', a: ['clear', 'opaque', 'bright', 'thin'], c: 1 },
  { cat: 'english', q: '"Not only ___ smart, but she is also kind."', a: ['she is', 'is she', 'she be', 'was she'], c: 1 },
  { cat: 'english', q: '"Once in a blue moon" means…', a: ['every night', 'very rarely', 'once a month', 'when sad'], c: 1 },
  { cat: 'english', q: 'The past participle of "take" is…', a: ['took', 'taken', 'taked', 'taking'], c: 1 },
  { cat: 'english', q: '"If I ___ you, I would study harder."', a: ['am', 'was', 'were', 'be'], c: 2 },
  { cat: 'english', q: 'A synonym of "brave" is…', a: ['scared', 'courageous', 'careful', 'quiet'], c: 1 },
  { cat: 'english', q: '"The homework ___ by Mary last night."', a: ['did', 'was done', 'is doing', 'has done'], c: 1 },
  { cat: 'english', q: '"Hit the books" means…', a: ['to fight', 'to study hard', 'to throw books', 'to buy books'], c: 1 },
  { cat: 'english', q: 'The opposite of "permanent" is…', a: ['forever', 'temporary', 'steady', 'lasting'], c: 1 },
  { cat: 'english', q: '"He suggested ___ early."', a: ['leave', 'to leave', 'leaving', 'left'], c: 2 },
  { cat: 'english', q: 'A group of wolves is called a…', a: ['pride', 'pack', 'school', 'swarm'], c: 1 },
  { cat: 'english', q: '"___ the rain, we still went hiking."', a: ['Because', 'Despite', 'Although', 'Since'], c: 1 },
  { cat: 'english', q: 'A person who can read and write is…', a: ['literate', 'illiterate', 'literal', 'literary'], c: 0 },
  { cat: 'english', q: '"She is interested ___ science."', a: ['on', 'in', 'at', 'for'], c: 1 },
  { cat: 'english', q: 'The prefix "re-" in "rewrite" means…', a: ['not', 'again', 'before', 'against'], c: 1 },
  { cat: 'english', q: '"Neither of the boys ___ here."', a: ['are', 'is', 'be', 'were'], c: 1 },
  { cat: 'english', q: 'The antonym of "expand" is…', a: ['extend', 'contract', 'explode', 'increase'], c: 1 },
  { cat: 'english', q: '"Break the ice" means…', a: ['to crack ice cubes', 'to start a conversation', 'to feel cold', 'to skate'], c: 1 },
  { cat: 'english', q: 'The plural of "ox" is…', a: ['oxes', 'oxen', 'oxs', 'oxies'], c: 1 },
  { cat: 'english', q: '"I have known him ___ ten years."', a: ['since', 'for', 'from', 'during'], c: 1 },
  { cat: 'english', q: 'The comparative form of "little" is…', a: ['littler', 'less', 'least', 'fewer'], c: 1 },
  { cat: 'english', q: '"He runs fast, ___ he?"', a: ['does', 'doesn\u2019t', 'isn\u2019t', 'don\u2019t'], c: 1 },
  { cat: 'english', q: 'A period of 100 years is a…', a: ['decade', 'century', 'millennium', 'season'], c: 1 },

  // ---- chinese ----
  { cat: 'chinese', q: '「塞翁失馬」的下一句是？', a: ['焉知非福', '必有後福', '不足為奇', '後悔莫及'], c: 0 },
  { cat: 'chinese', q: '「臥薪嘗膽」與哪位歷史人物有關？', a: ['劉備', '勾踐', '項羽', '韓信'], c: 1 },
  { cat: 'chinese', q: '「鞠躬盡瘁，死而後已」說的是哪位人物？', a: ['關羽', '諸葛亮', '曹操', '張飛'], c: 1 },
  { cat: 'chinese', q: '「莫等閒，白了少年頭」的下一句是？', a: ['空悲切', '誰人知', '歲月流', '志未酬'], c: 0 },
  { cat: 'chinese', q: '「青出於藍」比喻？', a: ['顏色漂亮', '學生勝過老師', '天空很藍', '染布的方法'], c: 1 },
  { cat: 'chinese', q: '「四面楚歌」與哪位人物有關？', a: ['劉邦', '項羽', '秦始皇', '孔子'], c: 1 },
  { cat: 'chinese', q: '「破釜沉舟」比喻？', a: ['煮飯技巧', '下定決心', '坐船旅行', '節省糧食'], c: 1 },
  { cat: 'chinese', q: '「諱疾忌醫」是指？', a: ['怕看醫生', '隱瞞缺點不肯改正', '生病要求醫', '醫術高明'], c: 1 },
  { cat: 'chinese', q: '「不入虎穴」的下一句是？', a: ['焉得虎子', '必有大難', '不見老虎', '便是英雄'], c: 0 },
  { cat: 'chinese', q: '「醉翁之意不在酒」比喻？', a: ['喝醉了', '別有目的', '酒不好喝', '愛喝酒的人'], c: 1 },
  { cat: 'chinese', q: '「紙上談兵」與哪位人物有關？', a: ['趙括', '岳飛', '孫武', '白起'], c: 0 },
  { cat: 'chinese', q: '「三顧草廬」是誰拜訪誰？', a: ['曹操拜訪司馬懿', '劉備拜訪諸葛亮', '孫權拜訪周瑜', '關羽拜訪張飛'], c: 1 },
  { cat: 'chinese', q: '「欲窮千里目」的下一句是？', a: ['更上一層樓', '黃河入海流', '白日依山盡', '不畏浮雲遮'], c: 0 },
  { cat: 'chinese', q: '「揠苗助長」的教訓是？', a: ['種田要勤力', '急於求成反而壞事', '幼苗要多澆水', '農作物要施肥'], c: 1 },
  { cat: 'chinese', q: '「杯弓蛇影」形容人？', a: ['眼力很好', '疑神疑鬼', '怕喝酒', '愛喝茶'], c: 1 },
  { cat: 'chinese', q: '「聞雞起舞」比喻？', a: ['雞叫得早', '勤奮自強', '愛跳舞', '養雞致富'], c: 1 },
  { cat: 'chinese', q: '「時間就是金錢」運用了哪種修辭手法？', a: ['擬人', '比喻', '誇張', '反問'], c: 1 },
  { cat: 'chinese', q: '「畫龍點睛」的意思是？', a: ['畫畫要仔細', '在關鍵處加上精彩一筆', '龍是神獸', '點眼睛最難畫'], c: 1 },
  { cat: 'chinese', q: '「水滴石穿」比喻？', a: ['水的力量大', '有恆心終能成事', '石頭很軟弱', '下雨的災害'], c: 1 },
  { cat: 'chinese', q: '《出師表》的作者是？', a: ['曹操', '諸葛亮', '司馬遷', '杜甫'], c: 1 },
  { cat: 'chinese', q: '《靜夜思》的作者是？', a: ['杜甫', '李白', '王維', '白居易'], c: 1 },
  { cat: 'chinese', q: '「先天下之憂而憂」出自哪位文人？', a: ['范仲淹', '蘇軾', '歐陽修', '王安石'], c: 0 },
  { cat: 'chinese', q: '「三人行，必有我師焉」出自？', a: ['《孟子》', '《論語》', '《大學》', '《中庸》'], c: 1 },
  { cat: 'chinese', q: '「歲寒三友」是指？', a: ['梅蘭菊', '松竹梅', '桃李杏', '蘭竹菊'], c: 1 },
  { cat: 'chinese', q: '「文房四寶」是指？', a: ['琴棋書畫', '筆墨紙硯', '詩詞歌賦', '梅蘭竹菊'], c: 1 },
  { cat: 'chinese', q: '「入木三分」原本形容什麼？', a: ['雕刻技術', '書法筆力', '武功高強', '釘子很長'], c: 1 },
  { cat: 'chinese', q: '「胸有成竹」的意思是？', a: ['胸口痛', '事前已有充分把握', '喜歡竹樹', '身材高大'], c: 1 },
  { cat: 'chinese', q: '「鶴立雞群」形容？', a: ['動物相處', '才能出眾', '雞場風光', '身材瘦削'], c: 1 },
  { cat: 'chinese', q: '「負荊請罪」是誰向誰請罪？', a: ['廉頗向藺相如', '張飛向關羽', '項羽向劉邦', '韓信向蕭何'], c: 0 },
  { cat: 'chinese', q: '「春風又綠江南岸」的下一句是？', a: ['明月何時照我還', '萬紫千紅總是春', '二月春風似剪刀', '春來江水綠如藍'], c: 0 },
  { cat: 'chinese', q: '「桃園結義」是哪三位人物？', a: ['劉備、關羽、張飛', '曹操、劉備、孫權', '諸葛亮、周瑜、魯肅', '趙雲、馬超、黃忠'], c: 0 },
  { cat: 'chinese', q: '司馬光小時候做過哪件著名的事？', a: ['破缸救友', '鑿壁偷光', '臥冰求鯉', '聞雞起舞'], c: 0 },
  { cat: 'chinese', q: '「只要功夫深，鐵杵磨成針」與哪位詩人有關？', a: ['杜甫', '李白', '白居易', '王維'], c: 1 },
  { cat: 'chinese', q: '「但願人長久」的下一句是？', a: ['千里共嬋娟', '明月幾時有', '把酒問青天', '低綺戶照無眠'], c: 0 },
  { cat: 'chinese', q: '「滿招損」的下一句是？', a: ['謙受益', '驕必敗', '盈則虧', '怒傷身'], c: 0 },
  { cat: 'chinese', q: '「孟母三遷」是為了？', a: ['逃避戰亂', '為孩子選擇好環境', '尋找工作', '探望親友'], c: 1 },
  { cat: 'chinese', q: '「一曝十寒」比喻？', a: ['天氣轉變', '做事沒有恆心', '曬太陽有益', '冬天寒冷'], c: 1 },
  { cat: 'chinese', q: '「望梅止渴」與哪位人物有關？', a: ['劉備', '曹操', '孫權', '袁紹'], c: 1 },
  { cat: 'chinese', q: '「投筆從戎」是指？', a: ['棄文從軍', '努力寫作', '參加考試', '畫畫參軍'], c: 0 },
  { cat: 'chinese', q: '「圍魏救趙」的軍師是？', a: ['孫臏', '龐涓', '韓信', '張良'], c: 0 },
  { cat: 'chinese', q: '「初唐四傑」不包括哪一位？', a: ['王勃', '楊炯', '盧照鄰', '李白'], c: 3 },
  { cat: 'chinese', q: '「天生我材必有用」的作者是？', a: ['李白', '杜甫', '蘇軾', '陸游'], c: 0 },
  { cat: 'chinese', q: '「春蠶到死絲方盡」的下一句是？', a: ['蠟炬成灰淚始乾', '東風無力百花殘', '相見時難別亦難', '夜吟應覺月光寒'], c: 0 },
  { cat: 'chinese', q: '「沉魚落雁」形容？', a: ['釣魚技術', '女子美貌', '雀鳥眾多', '海產豐富'], c: 1 },
  { cat: 'chinese', q: '「洛陽紙貴」比喻？', a: ['紙張短缺', '著作廣受歡迎', '物價上升', '洛陽繁華'], c: 1 },
  { cat: 'chinese', q: '「君子一言」的下一句是？', a: ['駟馬難追', '一言九鼎', '言而有信', '快馬一鞭'], c: 0 },
  { cat: 'chinese', q: '「臨渴掘井」比喻？', a: ['節約用水', '事到臨頭才準備', '挖井技術', '天旱無雨'], c: 1 },
  { cat: 'chinese', q: '「金石為開」的上一句是？', a: ['精誠所至', '專心致志', '持之以恆', '滴水穿石'], c: 0 },
  { cat: 'chinese', q: '「磨刀不誤砍柴工」的意思是？', a: ['磨刀很費時', '準備充足效率更高', '砍柴要快', '工具不重要'], c: 1 },
  { cat: 'chinese', q: '「螳螂捕蟬」的下一句是？', a: ['黃雀在後', '魚翁得利', '兩敗俱傷', '坐收其成'], c: 0 },

  // ---- general ----
  { cat: 'general', q: '香港在哪一年回歸中國？', a: ['1995', '1997', '1999', '2000'], c: 1 },
  { cat: 'general', q: '太陽系中最大的行星是？', a: ['地球', '土星', '木星', '火星'], c: 2 },
  { cat: 'general', q: '尖沙咀「1881」古蹟的前身是？', a: ['水警總部', '天文台', '郵政總局', '消防局'], c: 0 },
  { cat: 'general', q: '半島酒店位於哪條道路？', a: ['彌敦道', '梳士巴利道', '廣東道', '漆咸道'], c: 1 },
  { cat: 'general', q: '世界最高的山峰是？', a: ['富士山', '珠穆朗瑪峰', '玉山', '崑崙山'], c: 1 },
  { cat: 'general', q: '成年人體有大約多少塊骨頭？', a: ['106', '206', '306', '406'], c: 1 },
  { cat: 'general', q: '香港國際機場位於哪個島？', a: ['長洲', '赤鱲角', '南丫島', '坪洲'], c: 1 },
  { cat: 'general', q: '水的沸點是攝氏多少度？', a: ['90°C', '100°C', '110°C', '120°C'], c: 1 },
  { cat: 'general', q: '空氣中含量最多的氣體是？', a: ['氧氣', '氮氣', '二氧化碳', '氫氣'], c: 1 },
  { cat: 'general', q: '青馬大橋連接哪兩個地方？', a: ['青衣和馬灣', '青山和馬鞍山', '九龍和港島', '屯門和元朗'], c: 0 },
  { cat: 'general', q: '香港共分為多少個行政分區？', a: ['12', '15', '18', '21'], c: 2 },
  { cat: 'general', q: '九龍清真寺位於彌敦道與哪條街交界附近？', a: ['海防道', '北京道', '佐敦道', '柯士甸道'], c: 0 },
  { cat: 'general', q: '維多利亞港的名字源自？', a: ['英國維多利亞女王', '一位船長', '一座山', '一種花'], c: 0 },
  { cat: 'general', q: '尖沙咀星光大道紀念哪個行業的名人？', a: ['音樂', '電影', '體育', '科學'], c: 1 },
  { cat: 'general', q: '彩虹的形成是因為光的什麼現象？', a: ['反射', '折射與色散', '直線傳播', '吸收'], c: 1 },
  { cat: 'general', q: '重慶大廈由多少座 17 層大樓組成？', a: ['3', '4', '5', '6'], c: 2 },
  { cat: 'general', q: '光在真空中的速度大約是每秒？', a: ['3 萬公里', '30 萬公里', '300 萬公里', '3000 公里'], c: 1 },
  { cat: 'general', q: '香港第一條過海隧道是？', a: ['東區海底隧道', '紅磡海底隧道', '西區海底隧道', '獅子山隧道'], c: 1 },
  { cat: 'general', q: 'DNA 主要儲存在細胞的哪個部分？', a: ['細胞膜', '細胞核', '細胞質', '細胞壁'], c: 1 },
  { cat: 'general', q: '世界上最大的海洋是？', a: ['大西洋', '太平洋', '印度洋', '北冰洋'], c: 1 },
  { cat: 'general', q: '聲音在哪種介質中傳播最快？', a: ['空氣', '水', '固體', '真空'], c: 2 },
  { cat: 'general', q: '「光年」是量度什麼的單位？', a: ['時間', '距離', '速度', '亮度'], c: 1 },
  { cat: 'general', q: '世界最長的河流是？', a: ['長江', '尼羅河', '亞馬遜河', '黃河'], c: 1 },
  { cat: 'general', q: '人的心臟共有多少個腔室？', a: ['2 個', '3 個', '4 個', '5 個'], c: 2 },
  { cat: 'general', q: '植物進行光合作用時吸入哪種氣體？', a: ['氧氣', '二氧化碳', '氮氣', '氫氣'], c: 1 },
  { cat: 'general', q: '電壓的單位是？', a: ['安培', '伏特', '瓦特', '歐姆'], c: 1 },
  { cat: 'general', q: '香港最大的島嶼是？', a: ['香港島', '大嶼山', '南丫島', '長洲'], c: 1 },
  { cat: 'general', q: '澳洲的首都是？', a: ['悉尼', '墨爾本', '坎培拉', '布里斯班'], c: 2 },
  { cat: 'general', q: '哪種血型被稱為「萬能捐血者」？', a: ['A 型', 'B 型', 'AB 型', 'O 型'], c: 3 },
  { cat: 'general', q: '香港第一條鐵路是？', a: ['港島綫', '九廣鐵路', '荃灣綫', '輕鐵'], c: 1 },
  { cat: 'general', q: '人體最小的骨頭在哪個部位？', a: ['手指', '耳朵', '腳趾', '鼻子'], c: 1 },
  { cat: 'general', q: '香港回歸前由哪個國家管治？', a: ['法國', '英國', '葡萄牙', '荷蘭'], c: 1 },
  { cat: 'general', q: '太陽系中最小的行星是？', a: ['水星', '金星', '火星', '冥王星'], c: 0 },
  { cat: 'general', q: '植物光合作用時釋放出哪種氣體？', a: ['二氧化碳', '氧氣', '氮氣', '一氧化碳'], c: 1 },
  { cat: 'general', q: '世界上面積最大的國家是？', a: ['中國', '美國', '俄羅斯', '加拿大'], c: 2 },
  { cat: 'general', q: '聲音在空氣中每秒大約傳播多遠？', a: ['34 米', '340 米', '3400 米', '34000 米'], c: 1 },
  { cat: 'general', q: '香港大學位於哪一區？', a: ['薄扶林', '沙田', '觀塘', '元朗'], c: 0 },
  { cat: 'general', q: '蒸餾法可以分離什麼？', a: ['不同顏色', '沸點不同的液體', '大小石頭', '磁鐵與鐵'], c: 1 },
  { cat: 'general', q: '颱風的中心叫做？', a: ['風尾', '風眼', '風口', '風頭'], c: 1 },
  { cat: 'general', q: '哪種水果含豐富維他命 C？', a: ['橙', '薯仔', '白飯', '豆腐'], c: 0 },
  { cat: 'general', q: '香港天文台總部位於哪一區？', a: ['中環', '尖沙咀', '銅鑼灣', '沙田'], c: 1 },
  { cat: 'general', q: '大氣層最接近地面的一層叫？', a: ['平流層', '對流層', '中間層', '電離層'], c: 1 },
  { cat: 'general', q: '八達通卡在哪一年推出？', a: ['1995', '1997', '2000', '2003'], c: 1 },
  { cat: 'general', q: '中國古代四大發明不包括？', a: ['造紙術', '指南針', '火藥', '電燈'], c: 3 },
  { cat: 'general', q: '香港的紙幣由多少間銀行發行？', a: ['1 間', '2 間', '3 間', '4 間'], c: 2 },
  { cat: 'general', q: '奧運五環代表什麼？', a: ['五種運動', '五大洲', '五個國家', '五種顏色'], c: 1 },
  { cat: 'general', q: '自然界中最硬的物質是？', a: ['鋼鐵', '鑽石', '花崗岩', '黃金'], c: 1 },
  { cat: 'general', q: '月全食時月亮會呈現什麼顏色？', a: ['全黑', '暗紅色', '藍色', '銀白色'], c: 1 },
  { cat: 'general', q: '香港最高的山峰大帽山高約多少米？', a: ['557 米', '757 米', '957 米', '1157 米'], c: 2 },
  { cat: 'general', q: '聯合國總部設於哪個城市？', a: ['倫敦', '巴黎', '紐約', '日內瓦'], c: 2 },
];
