// ============================================================
// MEDIUM bank (P3–P4) — 200 questions, 50 per category.
// Level: multi-digit ×÷, fractions intro, perimeter & area,
// tenses & comparatives, idioms with stories.
// ============================================================
export const MEDIUM = [
  // ---- math ----
  { cat: 'math', q: '小明有 $50，買了 $18 的筆，剩多少錢？', a: ['$28', '$32', '$38', '$42'], c: 1 },
  { cat: 'math', q: '一盒有 12 粒糖，3 盒共有多少粒？', a: ['24', '30', '36', '48'], c: 2 },
  { cat: 'math', q: '45 ÷ 5 = ?', a: ['8', '9', '7', '6'], c: 1 },
  { cat: 'math', q: '2 小時 30 分鐘等於多少分鐘？', a: ['120', '150', '180', '230'], c: 1 },
  { cat: 'math', q: '長方形長 6cm、闊 4cm，周界是？', a: ['10 cm', '20 cm', '24 cm', '12 cm'], c: 1 },
  { cat: 'math', q: '7 × 8 = ?', a: ['54', '56', '63', '48'], c: 1 },
  { cat: 'math', q: '100 − 37 = ?', a: ['53', '63', '73', '67'], c: 1 },
  { cat: 'math', q: '哪個數可以被 3 整除？', a: ['25', '27', '28', '32'], c: 1 },
  { cat: 'math', q: '1 公斤等於多少克？', a: ['10', '100', '1000', '10000'], c: 2 },
  { cat: 'math', q: '2, 4, 8, 16, … 下一個數是？', a: ['18', '24', '32', '20'], c: 2 },
  { cat: 'math', q: '一星期返學 5 日，4 星期返學幾多日？', a: ['9', '16', '20', '24'], c: 2 },
  { cat: 'math', q: '時鐘長針指住 6，即是幾多分鐘？', a: ['6 分', '15 分', '30 分', '45 分'], c: 2 },
  { cat: 'math', q: '304 + 198 = ?', a: ['492', '502', '512', '402'], c: 1 },
  { cat: 'math', q: '600 − 258 = ?', a: ['342', '352', '442', '358'], c: 0 },
  { cat: 'math', q: '12 × 12 = ?', a: ['124', '144', '142', '154'], c: 1 },
  { cat: 'math', q: '96 ÷ 8 = ?', a: ['11', '12', '13', '14'], c: 1 },
  { cat: 'math', q: '18 的一半是多少？', a: ['8', '9', '10', '12'], c: 1 },
  { cat: 'math', q: '20 的 3/4 是多少？', a: ['12', '14', '15', '16'], c: 2 },
  { cat: 'math', q: '長方形長 8cm、闊 5cm，面積是？', a: ['13 cm²', '26 cm²', '40 cm²', '45 cm²'], c: 2 },
  { cat: 'math', q: '一年大約有多少個星期？', a: ['42', '48', '52', '56'], c: 2 },
  { cat: 'math', q: '1.5 小時等於多少分鐘？', a: ['75', '90', '105', '150'], c: 1 },
  { cat: 'math', q: '一個直角是多少度？', a: ['45°', '60°', '90°', '180°'], c: 2 },
  { cat: 'math', q: '1 公里等於多少米？', a: ['10', '100', '1000', '10000'], c: 2 },
  { cat: 'math', q: '5 張 $20 紙幣共值多少？', a: ['$25', '$100', '$120', '$200'], c: 1 },
  { cat: 'math', q: '48 粒糖平均分給 6 人，每人得幾粒？', a: ['6', '7', '8', '9'], c: 2 },
  { cat: 'math', q: '1, 1, 2, 3, 5, 8, … 下一個數是？', a: ['11', '12', '13', '16'], c: 2 },
  { cat: 'math', q: '15 分鐘是一小時的幾分之幾？', a: ['1/2', '1/3', '1/4', '1/5'], c: 2 },
  { cat: 'math', q: '三角形內角和是多少度？', a: ['90°', '180°', '270°', '360°'], c: 1 },
  { cat: 'math', q: '25 + 25 + 25 = ?', a: ['65', '70', '75', '85'], c: 2 },
  { cat: 'math', q: '雙數加雙數，結果一定是？', a: ['單數', '雙數', '質數', '負數'], c: 1 },
  { cat: 'math', q: '7 × 9 = ?', a: ['56', '63', '72', '81'], c: 1 },
  { cat: 'math', q: '84 ÷ 7 = ?', a: ['11', '12', '13', '14'], c: 1 },
  { cat: 'math', q: '456 + 278 = ?', a: ['724', '734', '744', '634'], c: 1 },
  { cat: 'math', q: '802 − 365 = ?', a: ['437', '447', '463', '537'], c: 0 },
  { cat: 'math', q: '正方形邊長 7cm，周界是？', a: ['14 cm', '21 cm', '28 cm', '49 cm'], c: 2 },
  { cat: 'math', q: '36 的 1/4 是多少？', a: ['6', '8', '9', '12'], c: 2 },
  { cat: 'math', q: '3/8 + 2/8 = ?', a: ['5/8', '5/16', '6/8', '1/8'], c: 0 },
  { cat: 'math', q: '1 小時 45 分鐘等於多少分鐘？', a: ['95', '105', '115', '145'], c: 1 },
  { cat: 'math', q: '一個月最多有多少日？', a: ['28', '30', '31', '32'], c: 2 },
  { cat: 'math', q: '4 × 6 ÷ 3 = ?', a: ['6', '8', '9', '12'], c: 1 },
  { cat: 'math', q: '1 米等於多少厘米？', a: ['10', '100', '1000', '60'], c: 1 },
  { cat: 'math', q: '$68 + $57 = ?', a: ['$115', '$125', '$135', '$121'], c: 1 },
  { cat: 'math', q: '一年有 4 季，每季大約有幾多個月？', a: ['2', '3', '4', '6'], c: 1 },
  { cat: 'math', q: '最大的雙位數是？', a: ['90', '98', '99', '100'], c: 2 },
  { cat: 'math', q: '10 個 $5 硬幣共值多少？', a: ['$15', '$50', '$55', '$105'], c: 1 },
  { cat: 'math', q: '100, 90, 80, … 下一個數是？', a: ['60', '70', '75', '85'], c: 1 },
  { cat: 'math', q: '鈍角是大於多少度的角？', a: ['30°', '45°', '60°', '90°'], c: 3 },
  { cat: 'math', q: '0 ÷ 8 = ?', a: ['0', '8', '1', '無法計算'], c: 0 },
  { cat: 'math', q: '最小的三位數是？', a: ['99', '100', '101', '111'], c: 1 },
  { cat: 'math', q: '32 人平均分成 4 組，每組有幾多人？', a: ['6', '7', '8', '9'], c: 2 },

  // ---- english ----
  { cat: 'english', q: 'The past tense of "go" is…', a: ['goed', 'went', 'gone', 'going'], c: 1 },
  { cat: 'english', q: '"She ___ to school every day."', a: ['go', 'goes', 'going', 'gone'], c: 1 },
  { cat: 'english', q: 'The plural of "child" is…', a: ['childs', 'childes', 'children', 'childrens'], c: 2 },
  { cat: 'english', q: 'Which word is a verb?', a: ['quickly', 'beautiful', 'jump', 'happiness'], c: 2 },
  { cat: 'english', q: '"The bird is flying ___ the sky."', a: ['in', 'on', 'at', 'under'], c: 0 },
  { cat: 'english', q: 'The opposite of "expensive" is…', a: ['dear', 'cheap', 'rich', 'poor'], c: 1 },
  { cat: 'english', q: '"I ___ my homework yesterday."', a: ['do', 'did', 'done', 'doing'], c: 1 },
  { cat: 'english', q: 'A baby cat is called a…', a: ['puppy', 'cub', 'kitten', 'calf'], c: 2 },
  { cat: 'english', q: 'Which is spelled correctly?', a: ['beutiful', 'beautiful', 'beautifull', 'butiful'], c: 1 },
  { cat: 'english', q: '"He is ___ than me."', a: ['tall', 'taller', 'tallest', 'more tall'], c: 1 },
  { cat: 'english', q: 'Which word rhymes with "cake"?', a: ['cat', 'lake', 'kick', 'cook'], c: 1 },
  { cat: 'english', q: '"We ___ TV last night."', a: ['watch', 'watched', 'watching', 'watches'], c: 1 },
  { cat: 'english', q: '"___ you like ice cream?"', a: ['Is', 'Do', 'Are', 'Am'], c: 1 },
  { cat: 'english', q: 'The opposite of "always" is…', a: ['sometimes', 'never', 'often', 'usually'], c: 1 },
  { cat: 'english', q: 'Which sentence is correct?', a: ['They is playing.', 'They are playing.', 'They am playing.', 'They be playing.'], c: 1 },
  { cat: 'english', q: '"There ___ many books on the shelf."', a: ['is', 'are', 'am', 'be'], c: 1 },
  { cat: 'english', q: 'Which word means "very big"?', a: ['tiny', 'huge', 'thin', 'short'], c: 1 },
  { cat: 'english', q: 'The past tense of "eat" is…', a: ['eated', 'ate', 'eaten', 'eating'], c: 1 },
  { cat: 'english', q: 'The sun rises in the ___.', a: ['west', 'north', 'east', 'south'], c: 2 },
  { cat: 'english', q: 'The past tense of "see" is…', a: ['seed', 'saw', 'seen', 'sawed'], c: 1 },
  { cat: 'english', q: '"How ___ water do you drink every day?"', a: ['many', 'much', 'often', 'long'], c: 1 },
  { cat: 'english', q: 'The opposite of "noisy" is…', a: ['loud', 'quiet', 'busy', 'angry'], c: 1 },
  { cat: 'english', q: '"He plays football ___ Saturdays."', a: ['in', 'at', 'on', 'by'], c: 2 },
  { cat: 'english', q: '"Tom is the ___ boy in our class."', a: ['tall', 'taller', 'tallest', 'most tall'], c: 2 },
  { cat: 'english', q: 'Choose the correct sentence:', a: ['She don\u2019t like milk.', 'She doesn\u2019t like milk.', 'She not like milk.', 'She doesn\u2019t likes milk.'], c: 1 },
  { cat: 'english', q: '"There isn\u2019t ___ time left."', a: ['many', 'much', 'few', 'lots'], c: 1 },
  { cat: 'english', q: 'A chef works in a ___.', a: ['hospital', 'kitchen', 'library', 'bank'], c: 1 },
  { cat: 'english', q: '"My father\u2019s sister is my ___."', a: ['uncle', 'aunt', 'cousin', 'grandma'], c: 1 },
  { cat: 'english', q: '"She sings ___."', a: ['beautiful', 'beautifully', 'beauty', 'beautify'], c: 1 },
  { cat: 'english', q: 'The plural of "leaf" is…', a: ['leafs', 'leaves', 'leafes', 'leave'], c: 1 },
  { cat: 'english', q: 'The past tense of "run" is…', a: ['runned', 'ran', 'run', 'running'], c: 1 },
  { cat: 'english', q: '"She ___ her teeth twice a day."', a: ['brush', 'brushes', 'brushing', 'brushed'], c: 1 },
  { cat: 'english', q: 'The plural of "tooth" is…', a: ['tooths', 'teeth', 'toothes', 'teeths'], c: 1 },
  { cat: 'english', q: '"I am taller ___ my brother."', a: ['then', 'than', 'that', 'as'], c: 1 },
  { cat: 'english', q: 'The opposite of "early" is…', a: ['fast', 'late', 'soon', 'slow'], c: 1 },
  { cat: 'english', q: '"We went ___ the museum yesterday."', a: ['to', 'at', 'on', 'in'], c: 0 },
  { cat: 'english', q: 'A baby sheep is called a…', a: ['calf', 'lamb', 'kid', 'foal'], c: 1 },
  { cat: 'english', q: 'Which spelling is correct?', a: ['becuase', 'because', 'becouse', 'beacause'], c: 1 },
  { cat: 'english', q: '"Look! He ___ football now."', a: ['plays', 'is playing', 'played', 'play'], c: 1 },
  { cat: 'english', q: 'Which word rhymes with "night"?', a: ['net', 'light', 'note', 'nut'], c: 1 },
  { cat: 'english', q: '"Tom and ___ went home together."', a: ['I', 'me', 'my', 'mine'], c: 0 },
  { cat: 'english', q: 'Which month comes after August?', a: ['July', 'September', 'October', 'June'], c: 1 },
  { cat: 'english', q: 'The opposite of "full" is…', a: ['hungry', 'empty', 'open', 'small'], c: 1 },
  { cat: 'english', q: '"May I have a glass ___ water?"', a: ['of', 'in', 'for', 'with'], c: 0 },
  { cat: 'english', q: 'A person who flies a plane is a…', a: ['driver', 'pilot', 'sailor', 'captain'], c: 1 },
  { cat: 'english', q: '"Did you ___ your homework?"', a: ['did', 'do', 'done', 'does'], c: 1 },
  { cat: 'english', q: 'Which word means "not difficult"?', a: ['hard', 'easy', 'heavy', 'busy'], c: 1 },
  { cat: 'english', q: 'The plural of "foot" is…', a: ['foots', 'feet', 'footes', 'feets'], c: 1 },
  { cat: 'english', q: 'The opposite of "buy" is…', a: ['get', 'sell', 'pay', 'keep'], c: 1 },
  { cat: 'english', q: '"She is good ___ drawing."', a: ['in', 'at', 'on', 'for'], c: 1 },

  // ---- chinese ----
  { cat: 'chinese', q: '「亡羊補牢」的意思是？', a: ['事後補救，未為晚也', '羊走失了很可惜', '修理欄柵很重要', '做事粗心大意'], c: 0 },
  { cat: 'chinese', q: '「春眠不覺曉」的下一句是？', a: ['花落知多少', '處處聞啼鳥', '夜來風雨聲', '低頭思故鄉'], c: 1 },
  { cat: 'chinese', q: '哪一個是「高興」的近義詞？', a: ['難過', '愉快', '生氣', '害怕'], c: 1 },
  { cat: 'chinese', q: '「畫蛇添足」是指？', a: ['畫畫很厲害', '多此一舉', '蛇有四隻腳', '做事很快'], c: 1 },
  { cat: 'chinese', q: '「日」字加一筆可以變成哪個字？', a: ['月', '目', '口', '田'], c: 1 },
  { cat: 'chinese', q: '「守株待兔」教訓我們不要？', a: ['勤力工作', '不勞而獲', '愛護動物', '砍伐樹木'], c: 1 },
  { cat: 'chinese', q: '「桃李滿門」形容什麼人？', a: ['農夫', '老師', '醫生', '商人'], c: 1 },
  { cat: 'chinese', q: '哪個成語形容速度很快？', a: ['一日千里', '守口如瓶', '井底之蛙', '對牛彈琴'], c: 0 },
  { cat: 'chinese', q: '「舉頭望明月」的下一句是？', a: ['低頭思故鄉', '疑是地上霜', '床前明月光', '花落知多少'], c: 0 },
  { cat: 'chinese', q: '「三心兩意」的反義詞是？', a: ['粗心大意', '一心一意', '心不在焉', '半途而廢'], c: 1 },
  { cat: 'chinese', q: '「虎頭蛇尾」是指做事？', a: ['有始有終', '有始無終', '快手快腳', '小心翼翼'], c: 1 },
  { cat: 'chinese', q: '哪一個字的部首是「火」？', a: ['河', '燒', '樹', '雪'], c: 1 },
  { cat: 'chinese', q: '「百聞不如一見」的意思是？', a: ['聽一百次更好', '親眼看見最真實', '不要相信別人', '見面要有禮貌'], c: 1 },
  { cat: 'chinese', q: '「雪中送炭」是指？', a: ['在困難時幫助別人', '冬天送禮物', '雪天買炭很貴', '天氣很寒冷'], c: 0 },
  { cat: 'chinese', q: '「光陰似箭」提醒我們要？', a: ['學習射箭', '珍惜時間', '走路要快', '努力儲錢'], c: 1 },
  { cat: 'chinese', q: '一（　）橋 — 應填哪個量詞？', a: ['條', '座', '張', '隻'], c: 1 },
  { cat: 'chinese', q: '「門庭若市」形容？', a: ['門口很小', '人多熱鬧', '市場很遠', '家裡冷清'], c: 1 },
  { cat: 'chinese', q: '「對牛彈琴」的意思是？', a: ['牛喜歡音樂', '白費唇舌', '彈琴好聽', '對動物要好'], c: 1 },
  { cat: 'chinese', q: '「床前明月光」的下一句是？', a: ['疑是地上霜', '低頭思故鄉', '舉頭望明月', '處處聞啼鳥'], c: 0 },
  { cat: 'chinese', q: '「東張西望」的意思是？', a: ['向東走向西走', '四處張望', '東西很多', '迷路了'], c: 1 },
  { cat: 'chinese', q: '「井底之蛙」形容人？', a: ['住在井裏', '見識少', '游水很好', '聲音很大'], c: 1 },
  { cat: 'chinese', q: '「自相矛盾」的意思是？', a: ['武器鋒利', '言行前後不一', '善於辯論', '買賣公平'], c: 1 },
  { cat: 'chinese', q: '「狐假虎威」是指？', a: ['狐狸怕老虎', '借別人威勢欺人', '老虎放假', '動物做朋友'], c: 1 },
  { cat: 'chinese', q: '「人山人海」形容？', a: ['山很高', '海很深', '人非常多', '風景優美'], c: 2 },
  { cat: 'chinese', q: '「一石二鳥」的意思是？', a: ['用石頭掟雀', '一舉兩得', '雀鳥很多', '打獵技術好'], c: 1 },
  { cat: 'chinese', q: '「守口如瓶」形容人？', a: ['口很小', '能保守秘密', '不愛說話', '喜歡喝水'], c: 1 },
  { cat: 'chinese', q: '「太陽公公出來了」運用了哪種修辭？', a: ['比喻', '擬人', '誇張', '對偶'], c: 1 },
  { cat: 'chinese', q: '「白雲像棉花糖」運用了哪種修辭？', a: ['比喻', '擬人', '誇張', '反問'], c: 0 },
  { cat: 'chinese', q: '一（　）剪刀 — 應填哪個量詞？', a: ['把', '張', '條', '架'], c: 0 },
  { cat: 'chinese', q: '「秋高氣爽」形容哪個季節？', a: ['春天', '夏天', '秋天', '冬天'], c: 2 },
  { cat: 'chinese', q: '「一舉兩得」的近義成語是？', a: ['一石二鳥', '一言九鼎', '一日千里', '一毛不拔'], c: 0 },
  { cat: 'chinese', q: '「口是心非」是指？', a: ['口齒伶俐', '心口不一', '說話大聲', '誠實可靠'], c: 1 },
  { cat: 'chinese', q: '「誰知盤中飧」的下一句是？', a: ['粒粒皆辛苦', '汗滴禾下土', '鋤禾日當午', '春種一粒粟'], c: 0 },
  { cat: 'chinese', q: '「鋤禾日當午」的下一句是？', a: ['汗滴禾下土', '粒粒皆辛苦', '誰知盤中飧', '秋收萬顆子'], c: 0 },
  { cat: 'chinese', q: '「目不轉睛」形容？', a: ['眼睛痛', '看得非常專注', '視力很好', '不想看'], c: 1 },
  { cat: 'chinese', q: '「七嘴八舌」形容？', a: ['七個人吃飯', '人多口雜', '舌頭靈活', '愛吃零食'], c: 1 },
  { cat: 'chinese', q: '哪一個字的部首是「水（氵）」？', a: ['海', '火', '木', '雲'], c: 0 },
  { cat: 'chinese', q: '哪一個字的部首是「心」？', a: ['看', '想', '聽', '行'], c: 1 },
  { cat: 'chinese', q: '「四通八達」形容？', a: ['樓宇高大', '交通方便', '人口眾多', '物價便宜'], c: 1 },
  { cat: 'chinese', q: '「異口同聲」的意思是？', a: ['口音不同', '大家說法一致', '聲音很大', '七嘴八舌'], c: 1 },
  { cat: 'chinese', q: '一（　）電影 — 應填哪個量詞？', a: ['齣', '條', '隻', '張'], c: 0 },
  { cat: 'chinese', q: '「半斤八兩」比喻？', a: ['重量很重', '不相上下', '買賣公平', '十分便宜'], c: 1 },
  { cat: 'chinese', q: '「五顏六色」形容？', a: ['顏色單調', '色彩繽紛', '五六個人', '顏料很貴'], c: 1 },
  { cat: 'chinese', q: '「度日如年」形容？', a: ['時間過得快', '日子難過', '一年很長', '生日快樂'], c: 1 },
  { cat: 'chinese', q: '「近朱者赤」的下一句是？', a: ['近墨者黑', '近水樓台', '近在眼前', '近鄉情怯'], c: 0 },
  { cat: 'chinese', q: '「百發百中」形容？', a: ['非常準確', '射箭很多', '百戰百勝', '速度很快'], c: 0 },
  { cat: 'chinese', q: '「孤掌難鳴」比喻？', a: ['手掌受傷', '獨力難成事', '不愛拍手', '安靜無聲'], c: 1 },
  { cat: 'chinese', q: '「火上加油」的意思是？', a: ['煮食技巧', '令事情更糟', '天氣炎熱', '燃料充足'], c: 1 },
  { cat: 'chinese', q: '「左鄰右里」是指？', a: ['左右手', '鄰居', '親戚', '同學'], c: 1 },
  { cat: 'chinese', q: '「拋磚引玉」是比喻？', a: ['亂掟東西', '用淺見引出高見', '建築方法', '尋找寶石'], c: 1 },

  // ---- general ----
  { cat: 'general', q: '尖沙咀鐘樓的前身是什麼建築的一部分？', a: ['消防局', '火車站', '郵政局', '燈塔'], c: 1 },
  { cat: 'general', q: '維多利亞港兩岸是哪兩個地方？', a: ['港島與九龍', '九龍與新界', '港島與離島', '沙田與大埔'], c: 0 },
  { cat: 'general', q: '香港區旗上是什麼花？', a: ['杜鵑花', '洋紫荊', '向日葵', '木棉花'], c: 1 },
  { cat: 'general', q: '水在攝氏多少度會結冰？', a: ['0°C', '10°C', '50°C', '100°C'], c: 0 },
  { cat: 'general', q: '彩虹有多少種顏色？', a: ['5', '6', '7', '8'], c: 2 },
  { cat: 'general', q: '人體最大的器官是？', a: ['心臟', '皮膚', '肺', '腦'], c: 1 },
  { cat: 'general', q: '地球繞太陽一圈需要多久？', a: ['一日', '一個月', '一年', '十年'], c: 2 },
  { cat: 'general', q: '港鐵荃灣綫是什麼顏色？', a: ['藍色', '綠色', '紅色', '紫色'], c: 2 },
  { cat: 'general', q: '熊貓最愛吃什麼？', a: ['竹', '蜜糖', '魚', '蘋果'], c: 0 },
  { cat: 'general', q: '香港島上被稱為「叮叮」的交通工具是？', a: ['巴士', '電車', '的士', '小巴'], c: 1 },
  { cat: 'general', q: '香港太空館位於哪一區？', a: ['中環', '尖沙咀', '旺角', '銅鑼灣'], c: 1 },
  { cat: 'general', q: '香港最高的山是？', a: ['獅子山', '太平山', '大帽山', '鳳凰山'], c: 2 },
  { cat: 'general', q: '植物製造養分主要靠什麼？', a: ['月光', '陽光', '電燈', '火'], c: 1 },
  { cat: 'general', q: '哪一個是香港的離島？', a: ['長洲', '沙田', '觀塘', '元朗'], c: 0 },
  { cat: 'general', q: '指南針指向哪兩個方向？', a: ['東西', '南北', '上下', '左右'], c: 1 },
  { cat: 'general', q: '蝴蝶是由什麼變成的？', a: ['蝌蚪', '毛毛蟲', '螞蟻', '蜜蜂'], c: 1 },
  { cat: 'general', q: '月亮會自己發光嗎？', a: ['會，好似太陽', '不會，反射太陽光', '晚上才發光', '夏天才發光'], c: 1 },
  { cat: 'general', q: '廟街夜市以什麼聞名？', a: ['滑雪場', '大牌檔與攤檔', '游泳池', '溫泉'], c: 1 },
  { cat: 'general', q: '昂坪 360 纜車在哪個島？', a: ['南丫島', '大嶼山', '長洲', '蒲台島'], c: 1 },
  { cat: 'general', q: '香港哪裡可以看大熊貓？', a: ['迪士尼', '海洋公園', '濕地公園', '太空館'], c: 1 },
  { cat: 'general', q: '水蒸發之後會變成？', a: ['冰', '水蒸氣', '雪', '泥'], c: 1 },
  { cat: 'general', q: '電燈泡是誰發明的？', a: ['牛頓', '愛迪生', '愛因斯坦', '貝爾'], c: 1 },
  { cat: 'general', q: '獅子山位於香港哪個部分？', a: ['港島', '九龍', '離島', '西貢'], c: 1 },
  { cat: 'general', q: '人類呼吸需要哪種氣體？', a: ['氮氣', '氧氣', '二氧化碳', '氫氣'], c: 1 },
  { cat: 'general', q: '港鐵觀塘綫是什麼顏色？', a: ['紅色', '綠色', '藍色', '黃色'], c: 1 },
  { cat: 'general', q: '颱風「八號波」懸掛時代表？', a: ['天氣良好', '烈風吹襲', '輕微落雨', '酷熱天氣'], c: 1 },
  { cat: 'general', q: '香港特別行政區成立紀念日是？', a: ['7月1日', '10月1日', '1月1日', '12月25日'], c: 0 },
  { cat: 'general', q: '太陽系有多少個行星？', a: ['7', '8', '9', '10'], c: 1 },
  { cat: 'general', q: '青蛙的幼體叫什麼？', a: ['蝌蚪', '毛蟲', '幼蟲', '魚苗'], c: 0 },
  { cat: 'general', q: '以夜景聞名的香港山頂是？', a: ['獅子山', '太平山頂', '大帽山', '飛鵝山'], c: 1 },
  { cat: 'general', q: '香港街上的郵筒是什麼顏色？', a: ['紅色', '綠色', '藍色', '黃色'], c: 1 },
  { cat: 'general', q: '香港電車行走在港島哪一邊？', a: ['北面', '南面', '東面', '山頂'], c: 0 },
  { cat: 'general', q: '冰融化之後會變成？', a: ['水蒸氣', '水', '雪', '鹽'], c: 1 },
  { cat: 'general', q: '人體哪個器官負責泵血？', a: ['肺', '心臟', '胃', '肝'], c: 1 },
  { cat: 'general', q: '蜘蛛有多少隻腳？', a: ['4', '6', '8', '10'], c: 2 },
  { cat: 'general', q: '香港天氣最凍通常是幾月？', a: ['4-5 月', '7-8 月', '1-2 月', '9-10 月'], c: 2 },
  { cat: 'general', q: '赤鱲角機場啟用前，香港的舊機場是？', a: ['石崗', '啟德', '屯門', '粉嶺'], c: 1 },
  { cat: 'general', q: '樹葉變黃落下多數在哪個季節？', a: ['春天', '夏天', '秋天', '冬天'], c: 2 },
  { cat: 'general', q: '世界最長的戶外行人電梯系統在？', a: ['中環至半山', '尖沙咀', '旺角', '沙田'], c: 0 },
  { cat: 'general', q: '蝙蝠通常在什麼時候活動？', a: ['中午', '晚上', '清晨', '下午'], c: 1 },
  { cat: 'general', q: '含羞草被觸碰時會？', a: ['開花', '合起葉子', '變色', '長高'], c: 1 },
  { cat: 'general', q: '地球上最大的動物是？', a: ['大象', '藍鯨', '長頸鹿', '鯊魚'], c: 1 },
  { cat: 'general', q: '香港的消防車是什麼顏色？', a: ['白色', '紅色', '綠色', '藍色'], c: 1 },
  { cat: 'general', q: '海水為什麼是鹹的？', a: ['含有鹽分', '魚的關係', '太陽曬的', '人放鹽落去'], c: 0 },
  { cat: 'general', q: '鳥類身上長有什麼？', a: ['鱗片', '羽毛', '甲殼', '尖刺'], c: 1 },
  { cat: 'general', q: '香港迪士尼樂園位於哪裡？', a: ['大嶼山', '西貢', '沙田', '南丫島'], c: 0 },
  { cat: 'general', q: '中國國旗上有多少粒星？', a: ['4', '5', '6', '7'], c: 1 },
  { cat: 'general', q: '奧運會每隔多少年舉行一次？', a: ['2 年', '3 年', '4 年', '5 年'], c: 2 },
  { cat: 'general', q: '萬里長城位於哪個國家？', a: ['日本', '中國', '韓國', '泰國'], c: 1 },
  { cat: 'general', q: '駱駝的駝峰儲存的主要是？', a: ['水', '脂肪', '食物', '空氣'], c: 1 },
];
