export function createGameState() {
  return {
    phase: 'start',
    playerName: '',
    difficulty: 'easy',
    score: 0,
    coinsCollected: 0,
    starsCollected: 0,
    chestsOpened: 0,
    streak: 0,
    startTime: 0,
    nearChest: null,
    nearCat: null,
    nearMtr: null,
    nearNpc: null,
    nearDog: false,
    boostUntil: 0,
    hitInvulnUntil: 0,
    dizzyUntil: 0,
    morning: true,
    sessionMode: 'full',
    chestGoal: 16,
    sessionTimed: true,
    sessionDurationSeconds: null,
    sessionDeadline: 0,
    sessionPausedAt: 0,
    trafficEnabled: true,
    stamps: { friend: false, park: false, mtr: false, first: false },
    stampSetBonus: false,
    wowUntil: 0,
  };
}
